version: '3.8'

services:
    
    mongodb:
        image: mongo
        container_name: mongo_api
        ports:
        - "27019:27017"
    
    mongo-seed:
        image: emartps/pyday-mongo
        depends_on:
        - mongodb